const actions = {
    GET_ORDERS: "GET_ORDERS",
    GET_COMPANIES: "GET_COMPANIES",
    GET_PAYMENT_TYPES: "GET_PAYMENT_TYPES",
    SAVE_ORDER: "SAVE_ORDER",
    SET_ERROR_ALERT: "SET_ERROR_ALERT",
    SET_SUCCESS_ALERT: "SET_SUCCESS_ALERT",
    SET_SUCCESS_ALERT_COUNTDOWN: "SET_SUCCESS_ALERT_COUNTDOWN"
}

export default actions;
