const mutations = {
    SET_ORDERS: "SET_ORDERS",
    SET_COMPANIES: "SET_COMPANIES",
    SET_ERROR_ALERT: "SET_ERROR_ALERT",
    SET_SUCCESS_ALERT: "SET_SUCCESS_ALERT",
    SET_SUCCESS_ALERT_COUNTDOWN: "SET_SUCCESS_ALERT_COUNTDOWN",
    SET_PAYMENT_TYPES: "SET_PAYMENT_TYPES",
    ADD_ORDER: "ADD_ORDER"
}

export default mutations;
